config/routes.rb
Photorails::Application.routes.draw do
  resources :devices

  resources :users

  resources :effects

  get '/photos/latest'
  get '/photos/update_canvas'
  get '/photos/photo_count'
  resources :photos

   match ':controller(/:action(/:id))(.:format)'
end

app/models/device.rb
class Device < ActiveRecord::Base
  attr_accessible :id, :setname
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  # GET /devices
  # GET /devices.json
  def index
    @devices = Device.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @devices }
    end
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
    @device = Device.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @device }
    end
  end

  # GET /devices/new
  # GET /devices/new.json
  def new
    @device = Device.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @device }
    end
  end

  # GET /devices/1/edit
  def edit
    @device = Device.find(params[:id])
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(params[:device])

    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
        format.json { render json: @device, status: :created, location: @device }
      else
        format.html { render action: "new" }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /devices/1
  # PUT /devices/1.json
  def update
    @device = Device.find(params[:id])

    respond_to do |format|
      if @device.update_attributes(params[:device])
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device = Device.find(params[:id])
    @device.destroy

    respond_to do |format|
      format.html { redirect_to devices_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_form.html.erb
<%= form_for(@device) do |f| %>
  <% if @device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% @device.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :setname %><br />
    <%= f.text_field :setname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/devices/edit.html.erb
<h1>Editing device</h1>

<%= render 'form' %>

<%= link_to 'Show', @device %> |
<%= link_to 'Back', devices_path %>

app/views/devices/index.html.erb
<h1>Listing devices</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Setname</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @devices.each do |device| %>
  <tr>
    <td><%= device.id %></td>
    <td><%= device.setname %></td>
    <td><%= link_to 'Show', device %></td>
    <td><%= link_to 'Edit', edit_device_path(device) %></td>
    <td><%= link_to 'Destroy', device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Device', new_device_path %>

app/views/devices/new.html.erb
<h1>New device</h1>

<%= render 'form' %>

<%= link_to 'Back', devices_path %>

app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @device.id %>
</p>

<p>
  <b>Setname:</b>
  <%= @device.setname %>
</p>


<%= link_to 'Edit', edit_device_path(@device) %> |
<%= link_to 'Back', devices_path %>