config/routes.rb
Photorails::Application.routes.draw do
  resources :devices

  resources :users

  resources :effects

  get '/photos/latest'
  get '/photos/update_canvas'
  get '/photos/photo_count'
  resources :photos

   match ':controller(/:action(/:id))(.:format)'
end

app/models/effect.rb
class Effect < ActiveRecord::Base
  attr_accessible :effectname, :id
end

app/controllers/effects_controller.rb
class EffectsController < ApplicationController
  # GET /effects
  # GET /effects.json
  def index
    @effects = Effect.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @effects }
    end
  end

  # GET /effects/1
  # GET /effects/1.json
  def show
    @effect = Effect.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @effect }
    end
  end

  # GET /effects/new
  # GET /effects/new.json
  def new
    @effect = Effect.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @effect }
    end
  end

  # GET /effects/1/edit
  def edit
    @effect = Effect.find(params[:id])
  end

  # POST /effects
  # POST /effects.json
  def create
    @effect = Effect.new(params[:effect])

    respond_to do |format|
      if @effect.save
        format.html { redirect_to @effect, notice: 'Effect was successfully created.' }
        format.json { render json: @effect, status: :created, location: @effect }
      else
        format.html { render action: "new" }
        format.json { render json: @effect.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /effects/1
  # PUT /effects/1.json
  def update
    @effect = Effect.find(params[:id])

    respond_to do |format|
      if @effect.update_attributes(params[:effect])
        format.html { redirect_to @effect, notice: 'Effect was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @effect.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /effects/1
  # DELETE /effects/1.json
  def destroy
    @effect = Effect.find(params[:id])
    @effect.destroy

    respond_to do |format|
      format.html { redirect_to effects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/effects_helper.rb
module EffectsHelper
end

app/views/effects/_form.html.erb
<%= form_for(@effect) do |f| %>
  <% if @effect.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@effect.errors.count, "error") %> prohibited this effect from being saved:</h2>

      <ul>
      <% @effect.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :effectname %><br />
    <%= f.text_field :effectname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/effects/edit.html.erb
<h1>Editing effect</h1>

<%= render 'form' %>

<%= link_to 'Show', @effect %> |
<%= link_to 'Back', effects_path %>

app/views/effects/index.html.erb
<h1>Listing effects</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Effectname</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @effects.each do |effect| %>
  <tr>
    <td><%= effect.id %></td>
    <td><%= effect.effectname %></td>
    <td><%= link_to 'Show', effect %></td>
    <td><%= link_to 'Edit', edit_effect_path(effect) %></td>
    <td><%= link_to 'Destroy', effect, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Effect', new_effect_path %>

app/views/effects/new.html.erb
<h1>New effect</h1>

<%= render 'form' %>

<%= link_to 'Back', effects_path %>

app/views/effects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @effect.id %>
</p>

<p>
  <b>Effectname:</b>
  <%= @effect.effectname %>
</p>


<%= link_to 'Edit', edit_effect_path(@effect) %> |
<%= link_to 'Back', effects_path %>