config/routes.rb
Photorails::Application.routes.draw do
  resources :devices

  resources :users

  resources :effects

  get '/photos/latest'
  get '/photos/update_canvas'
  get '/photos/photo_count'
  resources :photos

   match ':controller(/:action(/:id))(.:format)'
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :received, :shooting, :title
  attr_accessible :picture, :img
  attr_accessible :effect, :effectparam1, :effectparam2, :music
  #has_attached_file :picture, :styles => { :medium => "300x300>", :thumb => "100x100>"} 
  mount_uploader :img, ImgUploader
end

app/controllers/photos_controller.rb
# coding: utf-8
require 'kconv'

class PhotosController < ApplicationController

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @photos }
    end
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    @photo = Photo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/new
  # GET /photos/new.json
  def new
    @photo = Photo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/1/edit
  def edit
    @photo = Photo.find(params[:id])
  end

  # POST /photos
  # POST /photos.json
  def create
    if params[:photodata]
        h = Hash.new
        h[:img] = params[:photodata]
        h[:title] = params[:title]
        h[:received] = params[:received]
        h[:shooting] = params[:shooting]
        h[:effect] = params[:effect]
        h[:effectparam1] = params[:effectparam1]
        h[:effectparam2] = params[:effectparam2]
        h[:music] = params[:music]
        params[:photo] = h
    end

    @photo = Photo.new(params[:photo])

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render json: @photo, status: :created, location: @photo }
      else
        format.html { render action: "new" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /photos/1
  # PUT /photos/1.json
  def update
    @photo = Photo.find(params[:id])

    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to photos_url }
      format.json { head :no_content }
    end
  end

  # GET /photos/latest
  # GET /photos/latest.json
  def latest
    @photo = Photo.last
    @photos = Photo.all

    update_count() 

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @latest }
    end 
  end

  def update_canvas
    @photo = Photo.last
    @photos = Photo.all

    update_count() 

    respond_to do |format|
      format.html { render :partial => "canvas" }
    end
  end

  def photo_count
    update = false
    pc = PhotoCount.last
    if( pc.count != Photo.all.count)
      update = true
    end

    out = {'canvas_updated' => update ? 1 : 0 }

    respond_to do |format|
      format.json { render json: out }
    end    
  end

  def update_count
    pc = PhotoCount.last
    if( pc==nil )
      pc = PhotoCount.new
    end
    pc.count = Photo.all.size
    pc.save
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_canvas.html.erb
<!--
<p>
  count: <%= @photos.count %></br>
  img : <%= @photo.img_url.to_s %>
</p>
-->
<canvas width="1616" height="1080" id="demoimage"></canvas>

<script type="text/javascript">

const EFFECT_BLUR = "blur" ;
const EFFECT_EDGES = "edges";
const EFFECT_INVERT = "invert";
const EFFECT_NOISE = "noise";
const EFFECT_POINTILLIZE = "pointillize";
const EFFECT_EMBOSS = "emboss";
const EFFECT_SOLARIZE = "solarize";
const EFFECT_MOSAIC = "mosaic";
const EFFECT_VSLIP = "vslip" ;
const EFFECT_HSLIP = "hslip";
const EFFECT_TILE = "tile";

var can = document.getElementById("demoimage");
var context = can.getContext("2d");
//Image
var img = new Image();
img.src = "<%= @photo.img_url.to_s %>";
img.onload = function() {
	if ("<%= @photo.effect %>" == EFFECT_BLUR ){
		context.drawImage(img, 0, 0);
		blur();
	}
	else if ("<%= @photo.effect %>" == EFFECT_EDGES ){
		context.drawImage(img, 0, 0);
		edges();
	}
	else if ("<%= @photo.effect %>" == EFFECT_INVERT ){
		context.drawImage(img, 0, 0);
		invert();
	}
	else if ("<%= @photo.effect %>" == EFFECT_NOISE ){
		context.drawImage(img, 0, 0);
		noise(parseInt("<%= @photo.effectparam1 %>"));
	}
	else if ("<%= @photo.effect %>" == EFFECT_POINTILLIZE ){
		context.drawImage(img, 0, 0);
		pointillize(parseInt("<%= @photo.effectparam1 %>"));
	}
	else if ("<%= @photo.effect %>" == EFFECT_EMBOSS ){
		context.drawImage(img, 0, 0);
		emboss(parseInt("<%= @photo.effectparam1 %>"));
	}
	else if ("<%= @photo.effect %>" == EFFECT_SOLARIZE ){
		context.drawImage(img, 0, 0);
		solarize();
	}
	else if ("<%= @photo.effect %>" == EFFECT_MOSAIC  ){
		context.drawImage(img, 0, 0);
		mosaic(parseInt("<%= @photo.effectparam1 %>"));
	}
	else if ("<%= @photo.effect %>" == EFFECT_VSLIP ){
		context.drawImage(img, 0, 0);
		recon_ver( parseInt("<%= @photo.effectparam1 %>") );
	}
	else if ("<%= @photo.effect %>" == EFFECT_HSLIP ){
		context.drawImage(img, 0, 0);
		recon_hor(parseInt("<%= @photo.effectparam1 %>"));
	}
	else if ("<%= @photo.effect %>" == EFFECT_TILE){
		context.drawImage(img, 0, 0);
		recon_sqr(parseInt("<%= @photo.effectparam1 %>"));
	}
	else{
    	context.drawImage(img, 0, 0);
    }
};
</script>

<%= javascript_include_tag "effect" %>

app/views/photos/_form.html.erb
<%= form_for(@photo, :html => {:multipart => true})  do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :shooting %><br />
    <%= f.datetime_select :shooting %>
  </div>
  <div class="field">
    <%= f.label :received %><br />
    <%= f.datetime_select :received %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :img %><br />
    <%= f.file_field :img %>
  </div>
  <div class="effect">
    <%= f.label :effect %><br />
    <%= f.text_field :effect %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<h1>Listing photos</h1>

<table>
  <tr>
    <th>Shooting</th>
    <th>Received</th>
    <th>Title</th>
    <th>Img</th>
    <th>Effect</th>
    <th>Param1</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @photos.each do |photo| %>
  <tr class="<%= cycle('even', 'odd') %>">
    <td><%= photo.shooting %></td>
    <td><%= photo.received %></td>
    <td><%= photo.title %></td>
    <td><%= photo.img_url.to_s %></td>
    <td><%= photo.effect %></td>
    <td><%= photo.effectparam1 %></td>
    <td><%= link_to 'Show', photo %></td>
    <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
    <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Photo', new_photo_path %>
<%= link_to 'Latest', url_for(:action => 'latest') %>

app/views/photos/latest.html.erb
<h1>Latest photo</h1>

<p>
  <b>Title:</b>
  <%= @photo.title %>
</p>

<!--
<p>
  <b>Picture:</b>
  <%= image_tag @photo.img_url.to_s %>
</p>
-->

<div class="actiondemo">
<!--
<input type="button" onclick="demo();" value="Blur image">
<input type="button" onclick="recon_ver();" value="ReVer">
<input type="button" onclick="recon_hor();" value="ReHor">
<input type="button" onclick="recon_sqr();" value="ReSqr">
<input type="button" onclick="resetDemo();" value="Reset">
-->
  <div id="canvas">
    <%= render :partial => "canvas", 
      :locals => {:photo => @photo, :photos => @photos}, 
      :remote => true %>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function(){
  	  //updateCanvas();
    setInterval(updateCanvas, 1000);
  });

  function updateCanvas(){
    var canvas_updated = 0;

    $.ajaxSetup({async: false});
    $.getJSON("/photos/photo_count", function(data){
      canvas_updated = data.canvas_updated;
    });
    $.ajaxSetup({async: true});

    if(canvas_updated == 1){
      $("#canvas").load("/photos/update_canvas");
    }
  }
</script>

app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render 'form' %>


<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Shooting:</b>
  <%= @photo.shooting %>
</p>

<p>
  <b>Received:</b>
  <%= @photo.received %>
</p>

<p>
  <b>Title:</b>
  <%= @photo.title %>
</p>

<p>
  <b>Picture:</b>
  <%= image_tag @photo.img_url.to_s %>  
</p>

<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>

app/views/photos/update_canvas.html.erb
<%= render :partial => "canvas", 
      :locals => {:photo => @photo, :photos => @photos}, 
      :remote => true %>